api_platform:
    title:              'Bile-Mo API'
    description:        The Bile-Mo catalogue's API
    version:            '1.0.0'
    mapping:
        paths:          ['%kernel.project_dir%/src/Entity']
    collection:
      pagination:
        items_per_page: 10
