api_platform:
    title:              'Bile-Mo API'
    description:        The Bile-Mo catalogue's API
    version:            '1.0.0'
    mapping:
        paths:          ['%kernel.project_dir%/src/Entity']
    collection:
      pagination:
        items_per_page: 10
    swagger:
         api_keys:
             apiKey:
                name:   Authorization
                type:   header

    http_cache:
        etag:           true
        invalidation:
          enabled:      true
