api_platform:
    title:                'Bile-Mo API'
    description:          The Bile-Mo catalogue's API
    version:              '1.0.0'
    mapping:
        paths:            ['%kernel.project_dir%/src/Entity']
    collection:
      pagination:
        items_per_page:   10
    swagger:
         api_keys:
             apiKey:
                name:     Authorization
                type:     header

    http_cache:
        invalidation:
            enabled:      true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age:          3600
        shared_max_age:   3600
        public:           true
