security:
    encoders:
        App\Entity\Client:
            algorithm:           bcrypt

    providers:
        db_provider:
            entity:
                class:           App\Entity\Client
                property:        username

    role_hierarchy:
        ROLE_ADMIN:              ROLE_CLIENT

    firewalls:
        login:
            pattern:             ^/login
            stateless:           true
            anonymous:           true
            provider:            db_provider
            json_login:
                check_path:      /login_check
                username_path:   username
                password_path:   password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:             ^/
            provider:            db_provider
            stateless:           true
            anonymous:           true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern:             ^/(_(profiler|wdt)|css|images|js)/
            security:            false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: [ ROLE_CLIENT ] }
