version:              '3'
services:
    apache:
        build:        .docker/apache
        ports:
          - 8080:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-available
          - .:/home/wwwroot
        depends_on:
          - php

    mysql:
        image:        mysql:5.7
        volumes:
            - .docker/data/db:/var/lib/mysql

    php:
        build:        .docker/php
        volumes:
          - .:/home/wwwroot
        depends_on:
          - mysql

    phpmyadmin:
        image:        phpmyadmin/phpmyadmin
        environment:
          PMA_HOST:   mysql
          PMA_PORT:   3306
        ports:
            - 8081:80
        links:
            - mysql
    cache-proxy:
      build:          .docker/varnish
      depends_on:
        - apache
      volumes:
        - .docker/varnish/conf:/etc/varnish:ro
      ports:
        - "80:80"

    blackfire:
        image:        blackfire/blackfire
